### ISSUE TITLE
works with https://github.com/google/periph on a Rasp PI ?

### ISSUE THREAD

**Issue by gedw99** [maruel/msgbus#1]
SO that i can make the interfaces agnostic using mqtt.

I plan to have the main rasp PI be the Master. It also runs the GUI Server.
Slave Rasp PI's are connected to physical hardware.

MQTT is the messaging languages between them.

**Comment by maruel** [comment]
Yes it does. Make sure to use v3.0.5 as I just did an important bug fix.
